In [ ]:
import numpy as np  # Import Numpy and give it a shorthand

arr1 = np.array([1,5,7,33])              # Implicitly Typed integer array
arr2 = np.array([1.0,5,7,33])             # Implicitly Typed float array
arr3 = np.array([1,5,7,33], dtype='float') # Explicitly Typed float array
print(arr1)
print(arr2)
print(arr3)

## OUTPUT
# [ 1  5  7 33]
# [ 1.  5.  7. 33.]
# [ 1.  5.  7. 33.]

In [ ]:
import numpy as np

#Regular Array
arrPy = [range(i, i+5) for i in range(1,5)]
print(arrPy)

# Numpy Array
arrNp = np.array([range(i, i+5) for i in range(1,5)])
print(arrNp)

##########
# OUTPUT
# [range(1, 6), range(2, 7), range(3, 8), range(4, 9)]
# [[1 2 3 4 5]
#  [2 3 4 5 6]
#  [3 4 5 6 7]
#  [4 5 6 7 8]]
###########

In [ ]:
import numpy as np
validArr   = np.array([range(i-2,i+2) for i in range(2,5)])
print(validArr)
invalidArr = np.array([range(int(i/2),i*2) for i in range(2,5)])
#ERROR ENCOUNTERED
##################
# OUTPUT
#[[0 1 2 3]
# [1 2 3 4]
# [2 3 4 5]]
#<ipython-input-4-4eeb350620f9>:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
#  invalidArr = np.array([range(int(i/2),i*2) for i in range(2,5)])
##############################################################


In [ ]:
import numpy as np
dt = np.dtype({'names':('uName', 'uId', 'uEmail'),
          'formats':('U10', 'i4', 'U20')})
userData = np.zeros(3, dt)
#Creates an Structured Array with terms 'name', 'id', and email which are a 16 charaters string, 32 bit int and 32 character string respectivly.
userData['uName'] = ['Negative','Moon','Blue']
userData['uId'] =   [1,2,3]
userData['uEmail'] = ['Negative@gmail.com','Moon@gmail.com','Blue@gmail.com']
#FILLS THE ARRAY

print(userData['uName']) #Print all usernames
print(userData[0]) #Print the first entry
print(userData[-1]['uId']) # Print the Id of the last element

######
#OUTPUT
#['Negative' 'Moon' 'Blue']
#('Negative', 1, 'Negative@gmail.com')
#3
#######

In [10]:
import numpy as np
arr1 = np.random.randint(0,100, (3,3))
print(arr1)

print('-----------------------------------------')
# Sort along the colums
print(np.sort(arr1, axis=0))
print('-----------------------------------------')
# Sort Along the Rows
print(np.sort(arr1, axis=1))
print('-----------------------------------------')
# Sort whole Array by rows then columns
print(np.sort(np.sort(arr1), axis=0))
print('-----------------------------------------')
# Sort whole Array by Columns then rows
print(np.sort(np.sort(arr1, axis=0)))

[[32 76  1]
 [95 92 76]
 [30 75 63]]
-----------------------------------------
[[30 75  1]
 [32 76 63]
 [95 92 76]]
-----------------------------------------
[[ 1 32 76]
 [76 92 95]
 [30 63 75]]
-----------------------------------------
[[ 1 32 75]
 [30 63 76]
 [76 92 95]]
-----------------------------------------
[[ 1 30 75]
 [32 63 76]
 [76 92 95]]


In [26]:
import numpy as np
arr1 = np.random.random((5,5))
arr2 = np.random.random(5)

print(arr1,"\n",arr2)
#SUM
print(np.add.reduce(arr1))
print(np.add.accumulate(arr2))
print(arr1.sum(axis=1))
print(arr1.sum())
arr2 += 1 # uFun to add 1 to all values of arr2 and reassign
#POWER
print(np.power.accumulate(arr2))
# Stand Deviation and Varience
print(arr1.std())
print(arr2.var())
# Index of max/min
print(arr1.argmax()) # Is to find the mas of each sub array as this will print rowcolumne with no space
print(arr1.argmin())

[[0.67336848 0.17178476 0.94030908 0.15257246 0.74257853]
 [0.20917456 0.91132532 0.00736586 0.58191279 0.16805195]
 [0.27578636 0.41687174 0.61413864 0.53289707 0.02307563]
 [0.52531865 0.19114826 0.91523491 0.25310389 0.538879  ]
 [0.25670329 0.6615298  0.52004819 0.87967821 0.60668515]] 
 [0.02603621 0.2391786  0.4240816  0.73169064 0.2876162 ]
[1.94035134 2.35265989 2.99709668 2.40016442 2.07927027]
[0.02603621 0.26521481 0.68929641 1.42098705 1.70860325]
[2.68061332 1.87783048 1.86276944 2.42368471 2.92464464]
11.769542595298107
[1.02603621 1.03236332 1.04640234 1.08171302 1.1064282 ]
0.2810060427591307
0.05439174997540538
2
7


In [33]:
import numpy as np

arr1 = np.arange(3)
arr2 = np.ones(3)[:, np.newaxis] # Creates a column of ones
print(arr1,"\n",arr2)
print(arr1 + arr2)

[0 1 2] 
 [[1.]
 [1.]
 [1.]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
