In [7]:
# IMPORTS
import matplotlib.pyplot as plt # PLOTING
import numpy as np # NUMPY
import pandas as pd # PANDAS
from sklearn.datasets import load_iris # Dataset
from sklearn.metrics import accuracy_score # Metrics for analysis
# Model Validation Tools
from sklearn.model_selection import train_test_split 

# Models
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import RadiusNeighborsClassifier


In [8]:
# LOAD IRIS DATA
iris = load_iris()
X = iris.data
y = iris.target

In [9]:


## MODEL SETUP
model_1 = KNeighborsClassifier(n_neighbors=2)
model_1.fit(X, y)
y_model = model_1.predict(X)

print(accuracy_score(y, y_model))


0.98


In [10]:
#### CROSS VALIDATION ####
from sklearn.model_selection import cross_val_score
score = cross_val_score(model_1, X, y, cv=5)
score.mean()

0.9466666666666665

In [11]:
score

array([0.96666667, 0.93333333, 0.93333333, 0.9       , 1.        ])

In [7]:
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
import numpy as np
from numpy import nan
model = make_pipeline(SimpleImputer(strategy='mean'),
                      PolynomialFeatures(degree=2),
                      LinearRegression())
X = np.array([[nan, 0,   3],
                      [3,   7,   9],
                      [nan,   5,   nan],
                      [4,   nan, 6],
                      [nan,   8,   1],
                      [1, 1, 1],
                      [3, 4, 9]])
y = np.array([1,2,4,8,16,32,64])
model.fit(X, y)
print(y)
print(model.predict(X))

[ 1  2  4  8 16 32 64]
[ 1.  2.  4.  8. 16. 32. 64.]
